//The-King-Destroy 
const roles = {
'*Aventurero(a) - Novato(a) V* ✨': 0,
'*Aventurero(a) - Novato(a) IV* ✨': 2,
'*Aventurero(a) - Novato(a) III* ✨': 4,
'*Aventurero(a) - Novato(a) II* ✨': 6,
'*Aventurero(a) - Novato(a) I* ✨': 8,
'*Aventurero(a) del Valle V* 🗡️': 10,
'*Aventurero(a) del Valle IV* 🗡️': 12,
'*Aventurero(a) del Valle III* 🗡️': 14,
'*Aventurero(a) del Valle II* 🗡️': 16,
'*Aventurero(a) del Valle I* 🗡️': 18,
'*Caballero(a) del Alba V* 🏹': 20,
'*Caballero(a) del Alba IV* 🏹': 22,
'*Caballero(a) del Alba III* 🏹': 24,
'*Caballero(a) del Alba II* 🏹': 26,
'*Caballero(a) del Alba I* 🏹': 28,
'*Guardián(a) de los Bosques V* 🛡️': 30,
'*Guardián(a) de los Bosques IV* 🛡️': 32,
'*Guardián(a) de los Bosques III* 🛡️': 34,
'*Guardián(a) de los Bosques II* 🛡️': 36,
'*Guardián(a) de los Bosques I* 🛡️': 38,
'*Mago(a) del Crepúsculo V* 🔮': 40,
'*Mago(a) del Crepúsculo IV* 🔮': 42,
'*Mago(a) del Crepúsculo III* 🔮': 44,
'*Mago(a) del Crepúsculo II* 🔮': 46,
'*Mago(a) del Crepúsculo I* 🔮': 48,
'*Héroe(a) de la Corona V* 🎖️': 50,
'*Héroe(a) de la Corona IV* 🎖️': 52,
'*Héroe(a) de la Corona III* 🎖️': 54,
'*Héroe(a) de la Corona II* 🎖️': 56,
'*Héroe(a) de la Corona I* 🎖️': 58,
'*Paladín(a) del Alba V* ⚡': 60,
'*Paladín(a) del Alba IV* ⚡': 62,
'*Paladín(a) del Alba III* ⚡': 64,
'*Paladín(a) del Alba II* ⚡': 66,
'*Paladín(a) del Alba I* ⚡': 68,
'*Leyenda del Valle V* 🌀': 70,
'*Leyenda del Valle IV* 🌀': 72,
'*Leyenda del Valle III* 🌀': 74,
'*Leyenda del Valle II* 🌀': 76,
'*Leyenda del Valle I* 🌀': 78,
'*Soberano(a) del Reino V* 👑': 80,
'*Soberano(a) del Reino IV* 👑': 82,
'*Soberano(a) del Reino III* 👑': 84,
'*Soberano(a) del Reino II* 👑': 86,
'*Soberano(a) del Reino I* 👑': 88,
'*Titán(a) del Norte V* 🚀': 90,
'*Titán(a) del Norte IV* 🚀': 92,
'*Titán(a) del Norte III* 🚀': 94,
'*Titán(a) del Norte II* 🚀': 96,
'*Titán(a) del Norte I* 🚀': 98,
'*Guardían(a) de la Luz V* 🔅': 100,
'*Guardían(a) de la Luz IV* 🔅': 102,
'*Guardían(a) de la Luz III* 🔅': 104,
'*Guardían(a) de la Luz II* 🔅': 106,
'*Guardían(a) de la Luz I* 🔅': 108,
'*Maestro(a) de la Magia V* 🪄': 110,
'*Maestro(a) de la Magia IV* 🪄': 112,
'*Maestro(a) de la Magia III* 🪄': 114,
'*Maestro(a) de la Magia II* 🪄': 116,
'*Maestro(a) de la Magia I* 🪄': 118,
'*Señor(a) de la Guerra V* ⚔️': 120,
'*Señor(a) de la Guerra IV* ⚔️': 122,
'*Señor(a) de la Guerra III* ⚔️': 124,
'*Señor(a) de la Guerra II* ⚔️': 126,
'*Señor(a) de la Guerra I* ⚔️': 128,
'*Sabio(a) Eterno(a) V* 📜': 130,
'*Sabio(a) Eterno(a) IV* 📜': 132,
'*Sabio(a) Eterno(a) III* 📜': 134,
'*Sabio(a) Eterno(a) II* 📜': 136,
'*Sabio(a) Eterno(a) I* 📜': 138,
'*Viajero(a) del Multiverso V* ⏳': 140,
'*Viajero(a) del Multiverso IV* ⏳': 145,
'*Viajero(a) del Multiverso III* ⏳': 150,
'*Viajero(a) del Multiverso II* ⏳': 155,
'*Viajero(a) del Multiverso I* ⏳': 160,
'*Deidad de la Luz* 🔅': 170,
'*Deidad de la Eternidad* ⏳': 185,
'*Deidad de la Sabiduría* 📜': 200,
'*Deidad del Bosque* 🍃': 250,
'*Gran Monarca de las Sombras* 🌌': 300
}

let handler = m => m
handler.before = async function (m, { conn }) {
        let user = db.data.users[m.sender]
        let level = user.level
        let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
        user.role = role
        return !0

}
export default handler
